#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_weather_bus = env_modules.Clone()

env_weather_bus.add_source_files(env.modules_sources, "*.cpp")
